version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/app
    depends_on:
     - db
     
  db:  
    restart: always  
    image: postgres:latest
    environment:    
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=stockify
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: